apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pvmeez00m-go 
  janus-idp.io/tekton: pvmeez00m-go
  backstage.io/kubernetes-id: pvmeez00m-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pvmeez00m-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml